# Generated by Django 4.2.10 on 2024-08-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_pass_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='person',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='main.person'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='main.person'),
        ),
    ]
